version: "3.8"
services:
  confluence:
    build: .
    environment:
      - TZ=America/New_York
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn confluence.api.server:app --host 0.0.0.0 --port 8000 --reload

